# Generated by Django 2.2.13 on 2022-05-22 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220521_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='discounted_price',
            new_name='discount_price',
        ),
    ]
