# Generated by Django 2.2.13 on 2022-05-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220522_1508'),
        ('core', '0005_billingaddress'),
    ]

    operations = [
    ]
