# Generated by Django 2.2.13 on 2022-05-22 13:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_auto_20220522_1231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillingAddress',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='billing_address',
            new_name='address',
        ),
    ]
