# Generated by Django 2.2.13 on 2022-05-22 17:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_auto_20220522_1712'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='BillingAddress',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
    ]
