# Generated by Django 2.2.13 on 2022-05-22 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_auto_20220522_1754'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillingAddress',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='billing_address',
            new_name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Payment'),
        ),
    ]
